sensor_msgs/Image rgb
sensor_msgs/Image depth
sensor_msgs/Image mask
sensor_msgs/CameraInfo intrinsics
float32 volume
float32 semantic_id
---
bool valid false
geometry_msgs/Pose pose
float32[] shape_code
float32 scale
