# Files to read for processing.
rosbag_file: /data/datasets/khronos/mezzanine/khronos_mezzanine_long2.bag

# Intrinsic camera params.
fx: 372.4634094238281
fy: 371.5072021484375
cx: 315.9902073557914
cy: 254.59437002701452

# ROS parameters.
rgb_topic: /sparkal1/forward/color/image_raw/compressed
depth_topic: /sparkal1/forward/depth/image_rect_raw

# Algorithm params.
max_observation_distance: 5.0

# Output.
output_directory: /data/datasets/khronos/mezzanine/ground_truth
