# num_threads: 1 # this defaults to the number of cores on your machine if not set.
vertex_batch_size: 1000
# Threshold for accuracy/completeness and truncation distance for RMSE/MAD/Chamfer.
thresholds: [0.05, 0.08, 0.1, 0.2, 0.3, 0.5]
