# Configuration to run the entire processing pipeline of khronos. Will run all [change detectors X reconciliators] specified in the config.
# Data.
ground_truth_dsg_file: "/mnt/c/Users/DerFu/Documents/khronos/ground_truth/mezzanine/gt_dsg.sparkdsg"
ground_truth_background_file: "/mnt/c/Users/DerFu/Documents/khronos/ground_truth/apartment/gt_background.ply"
gt_changes_file: &gt_changes "/mnt/c/Users/DerFu/Documents/khronos/ground_truth/mezzanine/gt_changes.csv"

# Whetherto save the reconciled DSGs (these take some disk space).
save_reconciled_dsg: true

# Whether to write additional details for visualization.
save_visualization_detals: true

# Specify all change detectors to be run.
change_detection:
  # Everything in 'common' is used for all runs, overwritten by the specific runs below. At least one run must be specified.
  - name: common
    ray_verificator:
      verbosity: 0 #4 to show merges
      block_size: 0.5 # m
      radial_tolerance: 0.08 # m
      depth_tolerance: 0.5 # m
      ray_policy: Middle # First, Last, FirstAndLast, Middle, All
    ray_change_detector:
      temporal_resolution: 1.0 # s
      window_size: 5 # times the temporal_resolution
      absence_confidence: 0.5 # [0,1]
      presence_confidence: 0.5 # [0,1]
    objects:
      type: "RayObjectChangeDetector" # 'RayObjectChangeDetector'. Leave empty to not perform object change detection.
      time_filtering_threshold: 3.0 # s
    # background:
    #   type: "RayBackgroundChangeDetector" # 'RayBackgroundChangeDetector'. Leave empty to not perform background change detection.
    #   time_filtering_threshold: 3.0 # s

  # Experiments to run for change detection. These overwrite the common data.
  # - name: "L1"
  #   ray_verificator:
  #     depth_tolerance: 0.5 # m
  #   ray_change_detector:
  #     presence_confidence: 0.5 # [0,1]
  #     absence_confidence: 0.6 # [0,1]
  # - name: "L2"
  #   ray_verificator:
  #     depth_tolerance: 0.5 # m
  #   ray_change_detector:
  #     presence_confidence: 0.5 # [0,1]
  #     absence_confidence: 0.7 # [0,1]
  # - name: "M36"
  #   ray_verificator:
  #     depth_tolerance: 0.3 # m
  #   ray_change_detector:
  #     presence_confidence: 0.5 # [0,1]
  #     absence_confidence: 0.6 # [0,1]
  # - name: "M37"
  #   ray_verificator:
  #     depth_tolerance: 0.3 # m
  #   ray_change_detector:
  #     presence_confidence: 0.5 # [0,1]
  #     absence_confidence: 0.7 # [0,1]
  - name: "M48"
    ray_verificator:
      depth_tolerance: 0.4 # m
    ray_change_detector:
      presence_confidence: 0.5 # [0,1]
      absence_confidence: 0.8 # [0,1]



# Specify all reconciliators to be run.
reconciliation:
  # Everything in 'common' is used for all runs, overwritten by the specific runs below. At least one run must be specified.
  - name: common
    verbosity: 0 # 4 to show merges
    mesh_merger:
      type: change # overwrite, change
      remove_objects_from_background: true
      object_proximity_threshold: 0.1 # m
    time_estimates_conservative: false # Whether to use the conservative or optimistic time estimates.
    allow_overestimation: true
    merge_object_meshes: false

  - name: "Optimistic"
    merge_object_meshes: false

# Specify all evaluations to run.
evaluation:
  evaluate_mesh: false
  evaluate_objects: true

  mesh_evaluation:
    thresholds: [0.05, 0.1, 0.2, 0.5]

  object_evaluation:
    verbosity: 0 # 4 to show details
    match_require_semantics: true
    compensate_missegmentation: false
    changes_file: *gt_changes
    max_matching_distance: 2 # m, recommended: surface ~0.5, centroid ~2, bbox ~ 0
    association_method: Surface # Surface, Centroid, BoundingBox
    surface_subsampling_rate: 100
